
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.neftxx.evaluator;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int SIGA = 15;
  public static final int ADEC = 68;
  public static final int MENOR_QUE = 41;
  public static final int CLOSE = 73;
  public static final int READ = 75;
  public static final int LIT_ENTERO = 23;
  public static final int LLAVE_IZQ = 52;
  public static final int LIT_CHAR = 26;
  public static final int COR_IZQ = 47;
  public static final int POTENCIA = 34;
  public static final int PAR_DER = 46;
  public static final int MAYOR_QUE = 39;
  public static final int CONC = 66;
  public static final int IGUAL_IGUAL = 36;
  public static final int NOT = 44;
  public static final int ABRIR_VENTANA = 63;
  public static final int DEC = 5;
  public static final int LIT_BOOLEANO = 25;
  public static final int DOS_PUNTOS = 58;
  public static final int DIFERENTE_QUE = 37;
  public static final int ATXT = 65;
  public static final int RESERVAR = 61;
  public static final int RMENSAJE = 64;
  public static final int PUNTO_COMA = 49;
  public static final int WHEN = 20;
  public static final int IMPORTAR = 18;
  public static final int INCREMENTO = 56;
  public static final int COMA = 50;
  public static final int AENT = 67;
  public static final int ZRO = 2;
  public static final int MODULO = 33;
  public static final int WRITE = 71;
  public static final int NUEVO_GUI = 62;
  public static final int ALTO_ANCHO = 70;
  public static final int IGUAL = 35;
  public static final int PESO_DE = 60;
  public static final int EQLS = 69;
  public static final int WHILE = 8;
  public static final int WF = 72;
  public static final int SWITCH = 11;
  public static final int FOR = 9;
  public static final int DECREMENTO = 57;
  public static final int DIV = 32;
  public static final int LIT_STRING = 27;
  public static final int MULT = 31;
  public static final int DEFINIR = 16;
  public static final int ELSE = 22;
  public static final int MENOS = 30;
  public static final int MAS = 29;
  public static final int FUSION = 17;
  public static final int NULL = 21;
  public static final int PAR_IZQ = 45;
  public static final int EOF = 0;
  public static final int PUNTO = 51;
  public static final int REFERENCIA = 55;
  public static final int APEND = 74;
  public static final int DEFAULT = 13;
  public static final int LLAVE_DER = 53;
  public static final int COR_DER = 48;
  public static final int REPEAT = 10;
  public static final int MENOR_IGUAL_QUE = 40;
  public static final int BUL = 6;
  public static final int ENT = 3;
  public static final int ROMPER = 14;
  public static final int OR = 43;
  public static final int error = 1;
  public static final int REGRESAR = 19;
  public static final int CHR = 4;
  public static final int IF = 7;
  public static final int IMP = 59;
  public static final int ID = 28;
  public static final int UMENOS = 54;
  public static final int LIT_DECIMAL = 24;
  public static final int CASE = 12;
  public static final int MAYOR_IGUAL_QUE = 38;
  public static final int AND = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ZRO",
  "ENT",
  "CHR",
  "DEC",
  "BUL",
  "IF",
  "WHILE",
  "FOR",
  "REPEAT",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "ROMPER",
  "SIGA",
  "DEFINIR",
  "FUSION",
  "IMPORTAR",
  "REGRESAR",
  "WHEN",
  "NULL",
  "ELSE",
  "LIT_ENTERO",
  "LIT_DECIMAL",
  "LIT_BOOLEANO",
  "LIT_CHAR",
  "LIT_STRING",
  "ID",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "MODULO",
  "POTENCIA",
  "IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE_QUE",
  "MAYOR_IGUAL_QUE",
  "MAYOR_QUE",
  "MENOR_IGUAL_QUE",
  "MENOR_QUE",
  "AND",
  "OR",
  "NOT",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "PUNTO_COMA",
  "COMA",
  "PUNTO",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "UMENOS",
  "REFERENCIA",
  "INCREMENTO",
  "DECREMENTO",
  "DOS_PUNTOS",
  "IMP",
  "PESO_DE",
  "RESERVAR",
  "NUEVO_GUI",
  "ABRIR_VENTANA",
  "RMENSAJE",
  "ATXT",
  "CONC",
  "AENT",
  "ADEC",
  "EQLS",
  "ALTO_ANCHO",
  "WRITE",
  "WF",
  "CLOSE",
  "APEND",
  "READ"
  };
}

