
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.neftxx.olc;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int LLAVE_IZQ = 11;
  public static final int RUTA = 3;
  public static final int COMA = 14;
  public static final int FECHA_MOD = 8;
  public static final int CARPETA = 9;
  public static final int ARCHIVO = 7;
  public static final int LLAVE_DER = 12;
  public static final int CORRER = 5;
  public static final int PROYECTO = 2;
  public static final int STRING = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int DOS_PUNTOS = 13;
  public static final int NOMBRE = 4;
  public static final int CONFIGURACION = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROYECTO",
  "RUTA",
  "NOMBRE",
  "CORRER",
  "CONFIGURACION",
  "ARCHIVO",
  "FECHA_MOD",
  "CARPETA",
  "STRING",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "DOS_PUNTOS",
  "COMA"
  };
}

